<div class="container">
	<div class="row content">

		<div class="col-md-6 mb-3">
			<img src="img/img.png" alt="image" class="img-fluid">
		</div>

		<div class="col-md-6 mb-3">
			<h3 class="signin-text mb-3">Login</h3>
			<form action="/autenticar" method="POST">

				<div class="form-group">
					<label for="email"></label>
					<input type="text" class="form-control" placeholder="Email" name="email" id="email">
				</div>

				<div class="form-group">
					<label for="senha"></label>
					<input type="password" class="form-control" name="senha" placeholder="Senha" id="senha">
				</div>

				<button class="btn btn-class" type="submit">Logar</button>

				<div class="row" style="margin-top:10px">
					<div class="col">
						<a href="/cadastrar">Não tem uma conta? Cadastra-se agora.</a>
					</div>
				</div>

				<?php if($this->view->login =='erro'){?>
				<div class="row" style="margin-top:10px">
					<div class="col">
						<span class="text text-danger">*E-mail e ou senha inválidos!</span>
					</div>
				</div>
			<?php }?>
			</form>
		</div>

	</div>
</div>

<style>
	@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap');

body {
    font-family: 'Poppins', sans-serif;
    background-color: #00ac96;
}

.content {
    margin: 8%;
    background-color: #fff;
    padding: 4rem 1rem 4rem 1rem;
    box-shadow: 0 0 5px 5px rgba(0,0,0,.05);
}

.signin-text {
    font-family: normal;
    font-weight: 600 !important;
}

.form-control  {
    display: block;
    width: 100%;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    border-color: #00ac96 !important;
    border-style: solid !important;
    border-width: 0 0 1px 0 !important;
    color: #495057;
    height: auto;
    border-radius: 0;
    background-color: #fff;
    background-clip: padding-box;
}

.form-control:focus{
    color: #495057;
    background-color: #fff;
    border-color: #fff;
    outline: 0;
    box-shadow: none;
}

.btn-class{
    border-color: #00ac96;
    color:#00ac96;
}

.btn-class:hover {
    background-color: #00ac96;
    color: #fff;
}
</style>